#!/usr/bin/env python3
"""
Haiti Banking System 2.0 - Database Setup Script
This script helps you configure and initialize your database.
"""

import os
import sys
import secrets
from getpass import getpass

def print_header(text):
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")

def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_hex(32)

def create_env_file():
    """Interactive .env file creation"""
    print_header("Haiti Banking System 2.0 - Database Configuration")

    print("This script will help you set up your database configuration.\n")

    # Ask for database type
    print("Select your database type:")
    print("1. SQLite (Default - No setup required)")
    print("2. PostgreSQL (Recommended for production)")
    print("3. MySQL/MariaDB")
    print("4. Custom connection string")

    choice = input("\nEnter your choice (1-4) [1]: ").strip() or "1"

    if choice == "1":
        db_url = "sqlite:///haiti_bank.db"
        print("\n✓ SQLite selected - No additional configuration needed!")

    elif choice == "2":
        print("\n--- PostgreSQL Configuration ---")
        host = input("Database host [localhost]: ").strip() or "localhost"
        port = input("Database port [5432]: ").strip() or "5432"
        database = input("Database name [haiti_bank]: ").strip() or "haiti_bank"
        username = input("Database username [bankadmin]: ").strip() or "bankadmin"
        password = getpass("Database password: ")

        db_url = f"postgresql://{username}:{password}@{host}:{port}/{database}"
        print("\n✓ PostgreSQL configuration complete!")
        print("\nMake sure you have:")
        print("  1. Created the database: CREATE DATABASE haiti_bank;")
        print("  2. Created the user with proper permissions")
        print(f"  3. Installed psycopg2-binary: pip install psycopg2-binary")

    elif choice == "3":
        print("\n--- MySQL/MariaDB Configuration ---")
        host = input("Database host [localhost]: ").strip() or "localhost"
        port = input("Database port [3306]: ").strip() or "3306"
        database = input("Database name [haiti_bank]: ").strip() or "haiti_bank"
        username = input("Database username [bankadmin]: ").strip() or "bankadmin"
        password = getpass("Database password: ")

        db_url = f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
        print("\n✓ MySQL configuration complete!")
        print("\nMake sure you have:")
        print("  1. Created the database: CREATE DATABASE haiti_bank;")
        print("  2. Created the user with proper permissions")
        print("  3. Installed pymysql: pip install pymysql cryptography")

    elif choice == "4":
        print("\n--- Custom Connection String ---")
        db_url = input("Enter your database connection string: ").strip()
        print("\n✓ Custom database URL configured!")

    else:
        print("\n✗ Invalid choice. Defaulting to SQLite.")
        db_url = "sqlite:///haiti_bank.db"

    # Generate secret key
    print("\n--- Security Configuration ---")
    print("Generating secure SECRET_KEY...")
    secret_key = generate_secret_key()
    print(f"✓ Secret key generated: {secret_key[:16]}... (64 characters)")

    # Flask environment
    print("\nSelect Flask environment:")
    print("1. Development (with debugging)")
    print("2. Production (recommended for deployment)")

    env_choice = input("\nEnter your choice (1-2) [2]: ").strip() or "2"
    flask_env = "development" if env_choice == "1" else "production"

    # Create .env file
    env_content = f"""# Haiti Banking System 2.0 - Environment Configuration
# Generated by setup_database.py

# Secret key for session encryption (KEEP THIS SECRET!)
SECRET_KEY={secret_key}

# Database connection string
DATABASE_URL={db_url}

# Flask environment
FLASK_ENV={flask_env}

# Optional: Customize these settings
# BANK_NAME=Haiti National Bank
# CURRENCY=HTG
# MIN_TRANSFER_AMOUNT=1.0
# MAX_TRANSFER_AMOUNT=1000000.0
"""

    # Save .env file
    env_file = ".env"
    if os.path.exists(env_file):
        overwrite = input(f"\n{env_file} already exists. Overwrite? (y/n) [n]: ").strip().lower()
        if overwrite != 'y':
            env_file = ".env.new"
            print(f"\n✓ Configuration saved to: {env_file}")
            print(f"  Rename it to .env to use: mv {env_file} .env")

    with open(env_file, 'w') as f:
        f.write(env_content)

    print(f"\n✓ Configuration file created: {env_file}")

    return db_url, env_file == ".env"

def initialize_database():
    """Initialize the database tables"""
    try:
        from app import app, db
        from models import User, Account, Transaction

        print("\n--- Initializing Database ---")
        with app.app_context():
            print("Creating database tables...")
            db.create_all()
            print("✓ Database tables created successfully!")

            # Check if we should seed
            seed = input("\nWould you like to create a demo admin account? (y/n) [y]: ").strip().lower()
            if seed != 'n':
                # Check if admin already exists
                existing_admin = User.query.filter_by(username='admin').first()
                if existing_admin:
                    print("✗ Admin user already exists. Skipping...")
                else:
                    # Create admin user
                    admin = User(
                        username='admin',
                        email='admin@haitibank.ht',
                        first_name='Admin',
                        last_name='User',
                        phone='+509-1234-5678',
                        address='123 Main Street',
                        city='Port-au-Prince'
                    )
                    admin.set_password('admin123')
                    db.session.add(admin)
                    db.session.commit()

                    # Create admin account with initial balance
                    admin_account = Account(
                        account_number=Account.generate_account_number(),
                        account_type='checking',
                        balance=100000.0,
                        user_id=admin.id
                    )
                    db.session.add(admin_account)
                    db.session.commit()

                    print("\n✓ Demo admin account created!")
                    print(f"  Username: admin")
                    print(f"  Password: admin123")
                    print(f"  Account Number: {admin_account.account_number}")
                    print(f"  Initial Balance: G100,000.00")
                    print(f"\n⚠ IMPORTANT: Change the admin password after first login!")

            return True

    except Exception as e:
        print(f"\n✗ Error initializing database: {e}")
        print("\nPossible issues:")
        print("  1. Database server is not running")
        print("  2. Database credentials are incorrect")
        print("  3. Database does not exist (create it first)")
        print("  4. Required Python packages are not installed")
        print("\nCheck the DEPLOYMENT_GUIDE.md for more information.")
        return False

def test_connection():
    """Test database connection"""
    try:
        print("\n--- Testing Database Connection ---")
        from app import app, db

        with app.app_context():
            # Try to execute a simple query
            db.engine.execute('SELECT 1')
            print("✓ Database connection successful!")
            return True

    except Exception as e:
        print(f"✗ Database connection failed: {e}")
        return False

def main():
    """Main setup function"""
    try:
        # Check if we're in the right directory
        if not os.path.exists('app.py'):
            print("✗ Error: app.py not found!")
            print("  Please run this script from the Haiti Banking System directory.")
            sys.exit(1)

        # Create .env file
        db_url, env_created = create_env_file()

        if not env_created:
            print("\n⚠ Please rename your configuration file to .env and run this script again.")
            return

        # Ask if they want to initialize the database
        init = input("\nWould you like to initialize the database now? (y/n) [y]: ").strip().lower()
        if init != 'n':
            # Test connection
            if test_connection():
                # Initialize database
                if initialize_database():
                    print_header("Setup Complete!")
                    print("Your Haiti Banking System 2.0 is ready to use!\n")
                    print("Next steps:")
                    print("  1. Start the application: python app.py")
                    print("  2. Open your browser: http://localhost:5000")
                    print("  3. Login with the demo account (if created)")
                    print("  4. Review DEPLOYMENT_GUIDE.md for production setup")
                    print("\n" + "=" * 60)
                else:
                    print("\n⚠ Database initialization failed.")
                    print("  Please check the error messages above and try again.")
            else:
                print("\n⚠ Could not connect to database.")
                print("  Please verify your database configuration and try again.")
        else:
            print("\n✓ Configuration file created.")
            print("  Run 'flask init-db' or 'python app.py' to initialize the database.")

    except KeyboardInterrupt:
        print("\n\n✗ Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Unexpected error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
